# Generated by Django 5.1.2 on 2024-12-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_location_number_of_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(blank=True, choices=[('SV', 'Sea View'), ('CC', 'City Center'), ('MV', 'Mountain View')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='number_of_guests',
            field=models.CharField(blank=True, choices=[('16-30', '16 to 30'), ('2-6', '2 to 6'), ('7-15', '7 to 15'), ('30-50', '30 to 50')], max_length=10, null=True),
        ),
    ]
